### PR TITLE
Validating client certificate when handling a renewal request

### PR DESCRIPTION
**Pull request by petitout**

### CODE REVIEW

**Review by jessepeterson — CHANGES_REQUESTED** [review]
Sorry for the delay! Could you write a little about the problem you're trying to solve here? I'm not sure I understand the intent.

**Comment by NecatiMeral** [comment]
For enrollment requests, a challengePassword attribute of CSR is verified with the value known by the RA, while renewing certificates use their former certificate to authenticate RenewalReq messages.

So it should be possible to renew a certificate without the challenge (since it can be a one-time use only challenge).

**Comment by jessepeterson** [comment]
Hello @petitout! We removed our internal SCEP library in favor of the Smallstep fork in #233, which your PR here changes. You'd need to submit a PR upstream and then add support to this library (which I'm happy to take a look at). But for now I'll close this PR until those changes are made; feel free to re-open when/if it's ready. Cheers!

**Comment by nagappa2011** [comment]
Any latest update on this PR? Thank you.

**Pull request closed without merging**
