### PR TITLE
Add support for setting digest algo

### PR DESCRIPTION
**Pull request by nunoOliveiraqwe**
Golang 1.18 removed for sha1 signed certificates and this makes it impossible to use pkc7+go 1.18, because pkc7 defaults SHA1 hash function. [Go 1.18 Release Notes](https://tip.golang.org/doc/go1.18#sha1)

This pr adds support for setting the digest algo for pkc7 to use defaulting to SHA256 if none is specified.
Additionally go version is set to 1.18

### CODE REVIEW

**Comment by jessepeterson** [comment]
Have a look at https://github.com/micromdm/scep/pull/191#issuecomment-1835504965

tl;dr: SHA1 was supposed to be removed for _certificate signing_ in Go 1.18 but they accidentally broke all SHA-1 operations. They fixed this in Go 1.18.2. I.e. this should not be an issue today.

**Comment by nunoOliveiraqwe** [comment]
@jessepeterson  you are right. They rolled back the changes in go 1.18.1, I tested sha1 signatures in both, and as expected, it fails on 1.18 and passes 1.18.1. Leaving the link for the discussion here for documentation purposes, https://github.com/golang/go/issues/41682#issuecomment-1072695832

I still see same value in being able to set the digest algo. For example, when the target server forces a specific hash function to be used.

**Comment by nunoOliveiraqwe** [comment]
@jessepeterson I rolled back the dependency changes. Should be fine now.

**Comment by jessepeterson** [comment]
@nunoOliveiraqwe hello! we removed our scep library per [this comment](https://github.com/micromdm/scep/pull/227#issuecomment-1922127360) in #233. You'll need to submit any scep library changes upstream now in https://github.com/smallstep/scep. :) I'll close this PR for now, but if you update it with changes from upstream, feel free to re-open it. :)

**Pull request closed without merging**
